# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97ecdbca36755b75155131f55fda77830f116870472e7a6533234653ada57086c59f64ab4302bb6b6a1515907df46a66def491eec78269f0b7315ed409a6ace3

test:
  secret_key_base: d09c1c2d6028a82e9867ebcb97d32395098afcce1c30b844cfb63930ea9ddc45ff74344b157f08210196fae1cb4b53b8a54d68a7fab0bb9070d14c787957a550

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
